export const CHANGE_INPUT_TEXT = 'CHANGE_INPUT_TEXT';
export const CHANGE_INPUT_DATE = 'CHANGE_INPUT_DATE';
export const ADD_TASK = 'ADD_TASK';
export const CLICK_ACCEPT = 'CLICK_ACCEPT';
export const CLICK_DELETE = 'CLICK_DELETE';
export const HANDLE_REDACT_SUBMIT = 'HANDLE_REDACT_SUBMIT';
